server.servlet.context-path=/business
server.port=9095

pServidorU=localhost
pPortU=5432
pBdU=postgres
pPassU=nest-crud-2005
pDataBaseU=postgres

pServidor=localhost
pPort=5435
pBd=postgres
pPass=businessDev
pDataBase=bussines